[tool.black]
line-length = 88
target-version = ['py310']

[tool.ruff]
line-length = 88

[tool.ruff.isort]
lines-after-imports = 2

[tool.pytest.ini_options]
addopts = "--cov=src/fein --cov-report=term-missing"
